---
title: "isotope data"
author: "SC"
date: "`r Sys.time()`"
output: 
    bookdown::html_document2:
        code_folding: show
        section_numbers: true
        toc: true
        toc_depth: 3
        toc_float: true
---

# Isotope data

```{r}
fun_range <- function(x,n=100) {                              # Create user-defined function
  (x - min(x)) / (max(x) - min(x)) * 100
}
simpmatch  <-  function(i,j){
    if(length(i)>length(j)){
        tmp=i
        i=j
        j=tmp
    }
    length(na.omit(match(i,j)))
}
```
Get all shapefiles
```{r,eval=F}
allshapefiles=lapply(country,function(m) tmpm=readOGR(dsn = "Cartes/", layer=paste0(m,"_adm0") ))
seashapefile=do.call("rbind",allshapefiles)
```

```{r}
library(rgdal)
seashapefile=readOGR(dsn="Cartes/",layer="allsea")
```

```{r,out.width="50%"}
pryce=read.csv("data/DATA isotopie_Pryce_V2.csv")
pryce[,11:15]=apply(pryce[,11:15],2,as.numeric)
pryce=pryce[!is.na(pryce[,11]),]
isotopes=pryce[,11:15]
pryce.pca=prcomp(pryce[,11:15])
pryce.dist=dist(pryce.pca$x)
pryce.clust=hclust(pryce.dist)
pryce.kclust=cutree(pryce.clust,k=10) #playing comparing community cluster vs simple hierarchical clustering
plot(pryce.pca$x[,1:2],pch=21,bg=rainbow(10,alpha=.6)[pryce.kclust])
plot(pryce.pca$x[,1:2],pch=21,bg=rainbow(10,alpha=.6)[pryce.kclust])
text(pryce.pca$x[,1],pryce.pca$x[,2],pryce$Region,pch=21,bg=rainbow(10,alpha=.6)[pryce.kclust],cex=.4)


plot(pryce.pca$x[,1:2],pch=21,bg=rainbow(10,alpha=.6)[pryce.kclust])
plot(pryce.pca$x[,1:2],pch=21,bg=rainbow(10,alpha=.6)[pryce.kclust])
text(pryce.pca$x[,1],pryce.pca$x[,2],pryce$Site,pch=21,bg=rainbow(10,alpha=.6)[pryce.kclust],cex=.4)

pryce$Easting...Longitude= as.numeric(gsub("°","",pryce$Easting...Longitude))
pryce$Northing.Latitude= as.numeric(gsub("°","",pryce$Northing.Latitude))
plot(pryce$Easting...Longitude,pryce$Northing.Latitude,pch=21,bg=rainbow(10,alpha=.6)[pryce.kclust])

plot(pryce[,15:14],pch=21,bg=rainbow(10,alpha=.6)[pryce.kclust])
text(pryce[,15],pryce[,14],pryce$Site,pch=21,bg=rainbow(10,alpha=.6)[pryce.kclust],cex=.4)

ttt=dist(isotopes)
ttt=as.matrix(ttt)
dupli=which(apply(ttt,2,function(i)any(sum(i==0)>1)))

isotopes=isotopes[-as.numeric(dupli),]
pryce=pryce[-dupli,]

```

Tsnea and networks:
```{r,fig.height=20,fig.width=20}
nk=6

code=strsplit(pryce[,1],"/")
code=sapply(code,function(s)paste0(s[3:4],collapse="/"))


library(Rtsne)
isotopes.tsne=Rtsne(isotopes,pca=F)
isotopes.dist=dist(isotopes.tsne$Y)
isotopes.clust=hclust(isotopes.dist, method = "ward.D")
isotopes.kclust=cutree(isotopes.clust,k=nk) #playing comparing community cluster vs simple hierarchical clustering
plot(isotopes.tsne$Y[,1],isotopes.tsne$Y[,2],col=rainbow(nk)[isotopes.kclust],pch=20,xlab="PC1",ylab="PC2")
plot(isotopes.tsne$Y[,1],isotopes.tsne$Y[,2],col=rainbow(nk)[isotopes.kclust],pch=20,xlab="PC1",ylab="PC2",main="tSNE")

plot(isotopes.tsne$Y[,1],isotopes.tsne$Y[,2],col=rainbow(nk)[isotopes.kclust],pch=20,main="tSNE")
#text(isotopes.tsne$Y[,1],isotopes.tsne$Y[,2],pryce$Site,cex=.5)
text(isotopes.tsne$Y[,1],isotopes.tsne$Y[,2],code,cex=.5)
```

netowrsk

```{r}
library(igraph)
isotopes.ew=1/(exp(as.matrix(isotopes.dist)))
isotopes.graph=graph.adjacency(isotopes.ew, mode = "undirected", weighted = TRUE, diag = FALSE)
V(isotopes.graph)$label=as.character(pryce$Site)
V(isotopes.graph)$label.cex=.4
V(isotopes.graph)$size=8
V(isotopes.graph)$frame.color="black"
V(isotopes.graph)$frame.width=.5
V(isotopes.graph)$label.color=adjustcolor("black",.6)
E(isotopes.graph)$color=NA
isotopes.graph=set_graph_attr(isotopes.graph,"layout",layout_with_fr(isotopes.graph))
plot(isotopes.graph)
```

```{r louvain,results="hold",fig.cap="simple visualisation of the network with louvain communities. We label node given the site (left) and site + period (right)  where the artefact has been found.",out.width="50%",fig.show="hold",eval=F}
par(mar=c(0,0,0,0))
isotopes.louvain=cluster_louvain(isotopes.graph)
#while(length(table(isotopes.louvain$memberships[1,]))!=10)isotopes.louvain=cluster_louvain(isotopes.graph)
#isotopes.louvain=multilevel.community(isotopes.graph)
counts=as.data.frame(sort(table(isotopes.louvain$membership)))
colnames(counts)=c("community","size")
knitr::kable(counts)
plot(isotopes.graph,vertex.color=rainbow(length(isotopes.louvain),alpha=.6)[isotopes.louvain$membership])

plot(isotopes.graph,vertex.color=rainbow(length(isotopes.louvain),alpha=.6)[isotopes.louvain$membership],vertex.label=paste(pryce$Site,pryce$relative.period,sep="-"))

plot(seashapefile,lwd=0.1)
points(pryce$Easting...Longitude,pryce$Northing.Latitude ,pch=21,bg=rainbow(length(isotopes.louvain),alpha=.6)[isotopes.louvain$membership])
```

## Site Network

```{r,eval=F}
joined=cbind(pryce,louvain=isotopes.louvain$membership)
sites=unique(joined$Site)

system.time({
matdim1=sapply(sites,function(s1) sapply(sites,function(s2) simpmatch(joined$louvain[ joined$Site == s1],joined$louvain[ joined$Site == s2])))
})

system.time({
matdim2=matrix(NA,nrow=length(sites),ncol=length(sites))
for(s1 in 1:length(sites)){
    for(s2 in 1:length(sites)){
        c1=joined$louvain[ joined$Site == sites[s1]]
        c2=joined$louvain[ joined$Site == sites[s2]]
        matdim2[s1,s2]=simpmatch(c1,c2)
    }
}
})
sum(matdim2-matdim1)

sites.graph=graph.adjacency(matdim1, mode = "undirected", weighted = TRUE, diag = FALSE)
V(sites.graph)$label=as.character(sites)
V(sites.graph)$label.cex=.7
V(sites.graph)$size=8
V(sites.graph)$label.color="black"
E(sites.graph)$color=NA
sites.graph=set_graph_attr(sites.graph,"layout",layout_nicely(sites.graph))

```

visualise  communities of sites

```{r,out.width="100%"}
par(mar=c(0,0,0,0))
sites.communities=cluster_louvain(sites.graph)
comus=sites.communities$memberships[1,]

plot(sites.graph,vertex.color=rainbow(length(table(comus)),alpha=.6)[comus])
plot(seashapefile,lwd=0.1)
points(joined$Easting...Longitude,joined$Northing.Latitude ,pch=21,bg=rainbow(length(table(comus)),alpha=.6)[comus])

comus=sites.communities$memberships[2,]

plot(sites.graph,vertex.color=rainbow(length(table(comus)),alpha=.6)[comus])
plot(seashapefile,lwd=0.1)
points(joined$Easting...Longitude,joined$Northing.Latitude ,pch=21,bg=rainbow(length(table(comus)),alpha=.6)[comus])

```

Try ternary plots:

```{r,eval=F}
#install.packages("ggtern")
#devtools::install_git('https://bitbucket.org/nicholasehamilton/ggtern')
library(ggtern)

pryce[,13:15]=apply(pryce[,13:15],1,function(i)i/sum(i))
only=pryce[,c(13:15)]
colnames(only)=c("208Pb","207Pb","206Pb")
colnames(only)=c("A","B","C")
#only=t(apply(only,1,function(i)i/sum(i)))
onlys=as.data.frame(apply(only,2,fun_range,n=50))
only=as.data.frame(only)
par(xpd=T)
ggtern(onlys ,aes(A,B,C))+theme_bw()+ geom_point(color=as.numeric(as.factor(pryce$Region)))+geom_mask()
ggtern(only ,aes(A,B,C))+
geom_density_tern(aes(fill=as.numeric(as.factor(pryce$Region))),bins=10) + geom_point(color=as.numeric(as.factor(pryce$Region)))

#legend("topright",legend=unique(as.factor(pryce$Region)),col=unique(as.numeric(as.factor(pryce$Region))))

ggtern(onlys ,aes(A,B,C,color=pryce$Region)) +
  theme_bw() + geom_mask() +
  geom_point()


```

```{r,eval=F}

#  scale_T_continuous(limits=c(0.2,0.3),
#                     breaks=seq(0,1,by=0.01))+
#                     #labels=paste0("B",LETTERS[1:11])) + 
#  scale_L_continuous(limits=c(0.5,0.6),
#                     breaks=seq(0,1,by=0.01))+
#                     #labels=paste0("A",LETTERS[1:11])) + 
#  scale_R_continuous(limits=c(0.2,0.3),
#                     breaks=seq(0,1,by=0.01))
#                     #labels=paste0("C",LETTERS[1:11]))

ggtern(only ,aes(A,B,C))+geom_point(color=as.numeric(as.factor(pryce$Region)))+
  scale_T_continuous(limits=c(0.18,0.25),
                     breaks=seq(0,1,by=0.01))+
                     #labels=paste0("B",LETTERS[1:11])) + 
  scale_L_continuous(limits=c(0.54,0.6),
                     breaks=seq(0,1,by=0.01))+
                     #labels=paste0("A",LETTERS[1:11])) + 
  scale_R_continuous(limits=c(0.20,0.27),
                     breaks=seq(0,1,by=0.01))
 limit_tern(1.0,0.5,0.5)
tern_limits(.25,.8,.40)
geom_density_tern(aes(fill=..level..),bins=5) +
 geom_point()
plot(pryce[,11:12],col=as.factor(pryce$Region),pch=20)
plot3D(pryce[,11],pryce[,12],pryce[,15])

Ternary::TernaryPlot(xlim=c(-0.032,-0.01),ylim=c(.455,.465),padding=0,isometric=F)



data('Feldspar')
ggtern(Feldspar,aes(Ab,An,Or)) + 
 geom_density_tern(aes(color=..level..),bins=20) +
 geom_point()

df = data.frame(x = runif(50)*1000,
                y = runif(50)*1000,
                z = runif(50)*1000,
                Group = as.factor(round(runif(50,1,2))))
ggtern(data=df,aes(x,y,z),color=Group)
ggtern() + 
  geom_point(data = df, aes(x/10, y/10, z/10, color = Group)) + 
  labs(x="X", y="Y", z="Z", title="Title") +
  scale_T_continuous(breaks = seq(0,1,0.2), labels = 1000*seq(0,1,0.2)) +
  scale_L_continuous(breaks = seq(0,1,0.2), labels = 1000*seq(0,1,0.2)) +
  scale_R_continuous(breaks = seq(0,1,0.2), labels = 1000*seq(0,1,0.2))
```

